### ISSUE TITLE
Issue on compiling ckb-bf-zkvm

### ISSUE THREAD

**Issue by XuJiandong** [xxuejie/ckb-contract-toolchains#1]
Try to build: https://github.com/cryptape/ckb-bf-zkvm/tree/main
```
make ci
```

See output here: https://pastebin.com/XRpyzAsg

Special configuration for ckb-c-stdlib: https://github.com/cryptape/ckb-bf-zkvm/blob/2711b6f33d602899bbc4a0416a4e4302ed90231f/ckb_bf_verifier/Cargo.toml#L9

**Comment by XuJiandong** [comment]
It's triggered by this PR: https://github.com/nervosnetwork/ckb-std/pull/30/files

**Comment by xxuejie** [comment]
The version 0.12.1 of ckb-std should resolve this problem. Tho it might be needed to enable `dummy-libc` feature manually.
