### ISSUE TITLE
Consider adding support for "os::ffi"

### ISSUE THREAD

**Issue by XuJiandong** [xxuejie/ckb-contract-toolchains#2]
While compiling [uint](https://github.com/paritytech/parity-common/blob/master/uint/Cargo.toml) examples by:

```
$ cargo build --example modular --target riscv64imac_zba_zbb_zbc_zbs-unknown-ckb-elf

error[E0433]: failed to resolve: use of undeclared crate or module `os`
  --> /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/os_str_bytes-6.5.0/src/common/mod.rs:20:5
   |
20 | use os::ffi::OsStrExt;
   |     ^^ use of undeclared crate or module `os`

error[E0433]: failed to resolve: use of undeclared crate or module `os`
  --> /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/os_str_bytes-6.5.0/src/common/mod.rs:21:5
   |
21 | use os::ffi::OsStringExt;
   |     ^^ use of undeclared crate or module `os`
```

**Comment by xxuejie** [comment]
I'm adding `std::os::ckb::ffi` package now, which shall be available in the next build. That being said, one thing I noticed, is that other crates (such as `atty`) fails in the build process here as well. We could of course patch `os_str_bytes`, `atty` and other failing crates as well, but an alternative path that works now, is that we can comment out [this line](https://github.com/paritytech/parity-common/blob/27b17c0d5d32ebf384dd4b535d9045598904519d/uint/Cargo.toml#L33), this is not needed by uint example. When this dependency is removed, uint example can be built using ckb Rust toolchain without problems, and the resulting binary could run on ckb-debugger as well.

**Comment by xxuejie** [comment]
Version `20230331-2` now has `std::os::ckb::fii` package added.
